export enum ExternalMessageEnum {
  MESSAGE = 'MESSAGE',
  LI_PROFILE = 'LINKEDIN_PROFILE',
  LI_CONNECTION = 'LINKED_CONNECTION',
  LI_TOTAL_CONNECTION = 'LINKED_TOTAL_CONNECTION',
  LI_GLOBAL_SEARCH = 'SEARCH_PROFILE',
  LI_LOCATION = 'LOCATION',
}
