import type { Metadata } from 'next';
import '../styles/main.scss';
import '../styles/globals.scss';
import Providers from '../store/Providers';
import Navbar from '../component/Navbar/Navbar';
import QueryProvider from './QueryProvider';
import Extensionsignal from '../component/Extensionsignal/index';

export const metadata: Metadata = {
  title: 'Bussiness Development App',
  description: 'Generated by Bussiness Development App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <QueryProvider>
          <Providers>
            <Extensionsignal />
            <Navbar />
            {children}
          </Providers>
        </QueryProvider>
      </body>
    </html>
  );
}
