import type { Metadata } from 'next';
import '../styles/main.scss';
import '../styles/globals.scss';
import 'qlu-20-ui-library/dist/build/index.css';
import Providers from '../provider';
import Navbar from '../components/header/header';
import QueryProvider from './QueryProvider';
import Extensionsignal from '../components/extensionSignal/index';
import MultiSidebar from '@/components/multSlideBar/multiSlidebar';

export const metadata: Metadata = {
  title: 'Bussiness Development App',
  description: 'Generated by Bussiness Development App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <QueryProvider>
          <Providers>
            {/* TODO: Name Convention Fixed*/}
            <Extensionsignal />
            <Navbar />
            <MultiSidebar />
            {children}
          </Providers>
        </QueryProvider>
      </body>
    </html>
  );
}
